### ISSUE TITLE
Enhancement: view announcement/sticky from the main board

### ISSUE THREAD

**Issue by lhbt** [brunoais/phpbbextf_read_other#12]
Hello,

I have an "Applications" forum on which the "Read others topics" permission is set to "no". When users subject to that permission are in the forum, they can see an annoucement post in it. 
However from the main board all they see is "Classified information" - I think they should be able to see the sticky if they don't have an application post in there. 

https://gyazo.com/3dda760a6820d8451801e54646831794 - main board view
https://gyazo.com/d230d86ebb72457b8b800005cca95a71 - forum view

Would that be a possible improvement or am I using the extension wrong?

Cheers,
Laurent

**Comment by brunoais** [comment]
I already tried this and it gives me a whole bunch of issues.
Solving such problem with phpBB's hooks (maybe even if there was more information without fetching unused data) is too much resource intensive. It used to do just that but it no longer does due to bugs in the previous implementation.

I will investigate if there's changes there which allow it now.

**Comment by brunoais** [comment]
I already tried this and it gives me a whole bunch of issues.
Solving such problem with phpBB's hooks (maybe even if there was more information without fetching unused data) is too much resource intensive. It used to do just that but it no longer does due to bugs in the previous implementation.

I will investigate if there's changes there which allow it now.

**Comment by brunoais** [comment]
I was unable to get the time to check this out.
Now a version is out, I will get some urgent stuff out of the way and then look into this.

**Comment by brunoais** [comment]
Not easy to do.
How much do you need this?

**Comment by 3D-I** [comment]
I think it is alright as it is.

If you set a post to be an announcement associated with that forum, all users will be able to see it.

Setting as a sticky will only sticky the topic but the permission’s rules maintain.

**Comment by brunoais** [comment]
You are fine and the other user didn't answer for very long. I'll just close this
