### ISSUE TITLE
changes unread posts number for users without permission to read posts

### ISSUE THREAD

**Issue by mvolkening** [brunoais/phpbbextf_read_other#6]
First, thanks for the great extension!

I noticed that for users that don't have permission to read the topics, the unread posts count includes the unread posts in the forum that is hidden. For them the "mark all read" never reduces the count to "0" even so they have no other posts unread.
I'm not even sure if this is a bug, but I would expect it to behave the same as if a user is not allowed to see a certain category, the posts in them are also not counted to the "unread posts" count. 
Any help is much appreciated.

**Comment by AlSarsawi** [comment]
yes .. i just came here to open same issue

**Comment by brunoais** [comment]
Ups. I missed this one, somehow.
I'm dealing with a dead relative about now and work is nearly killing me with the time I have to dedicate to it and the learning I have to show I'm doing.
I no longer have an ETA for this, unfortunately. I will do it when I get a gap on my agenda, which I have at times.
Regardless, I have some rewriting to do due to the limitations of extensions in phpBB which is throwing me back on the ETA time even more...

**Comment by brunoais** [comment]
This should be fixed now.
https://github.com/brunoais/phpbbextf_read_other/commit/ca24f1219bfce3f8cf0d9b6640366706b6d61faa
I'm now doing some finishing touches to version 1.0
